import type { Metadata } from "next";

import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import NavCart from "@/components/shared/NavCart";
import Footer from "@/components/shared/Footer";

export const metadata: Metadata = {
  title: "Next Auth",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
    <head>
      {/* Add the Google Fonts link here */}
      <link
        rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Marcellus&family=Jost:wght@400;700&family=Roboto:wght@400;700&family=Space+Mono&family=Montserrat&family=Courier+Prime&family=Poppins:wght@400;700&family=Raleway:wght@400;700&family=Nunito+Sans:wght@400;700&family=Playfair+Display:wght@400;700&family=Lora:wght@400;700&family=Abril+Fatface&family=Pacifico&display=swap"
      />
    </head>
    <body>
      <Navbar />
      <NavCart />
      <div className="min-h-screen">{children}</div>
      <Footer></Footer>
    </body>
  </html>
  );
}
